### ISSUE TITLE
Animations are not working in IE11

### ISSUE THREAD

**Issue by genextwebs** [Tusko/WP-Anatomy#2]
Hello,
          I am using this this WP theme starter in my site & I found that animations aren't working in IE11 and it doesn't load the content due to it (animated, fadeIn etc classes are not working), do you have any fix for the same?

Thanks.

**Comment by Tusko** [comment]
Hello @genextwebs 
I'm using css3animateit for 3 years and have never had problems with it.

can you provide some code, how did you do that?

**Comment by genextwebs** [comment]
Thanks for the reply. Here is my website.

http://www.fllitigation.com/

If you open it in IE 11 then it won't load the content, however if you open the same in Chrome, Firefox, Safari or Edge it works & if I disable animation classes via console in IE 11 it loads content properly. 

Thanks.

**Comment by genextwebs** [comment]
By the way, I managed to get the content in IE by putting up condition for not to load animate classes for IE but it has disabled all the animations in it, so do you have any fix for the same? Thanks again!

**Comment by Tusko** [comment]
changed to AOS
